import 'package:flutter/material.dart';
import '../models/request_model.dart';
import '../services/database_service.dart';

class RequestProvider with ChangeNotifier {
  final DatabaseService _dbService = DatabaseService();
  List<RequestModel> _myRequests = [];
  List<RequestModel> _incomingRequests = [];
  bool _isLoading = false;
  String? _errorMessage;

  List<RequestModel> get myRequests => _myRequests;
  List<RequestModel> get incomingRequests => _incomingRequests;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  Future<void> fetchMyRequests(String recipientId) async {
    _setLoading(true);
    try {
      _myRequests = await _dbService.getRequestsByRecipient(recipientId);
      _errorMessage = null;
    } catch (e) {
      _errorMessage = e.toString();
    } finally {
      _setLoading(false);
    }
  }

  Future<void> fetchIncomingRequests(String donorId) async {
    _setLoading(true);
    try {
      _incomingRequests = await _dbService.getRequestsByDonor(donorId);
      _errorMessage = null;
    } catch (e) {
      _errorMessage = e.toString();
    } finally {
      _setLoading(false);
    }
  }

  Future<bool> createRequest({
    required String postId,
    required String recipientId,
    required String donorId,
    String? message,
  }) async {
    _setLoading(true);
    try {
      // Need to construct RequestModel or pass fields to DB service.
      // DatabaseService.createRequest takes a model.
      // I'll create the model here.
      // ID will be generated by DB or Service, but model needs one.
      // I'll use empty string or generate UUID if needed. 
      // Assuming Service handles it or I provide one.
      final newRequest = RequestModel(
        requestId: '', // DB should assign or override
        postId: postId,
        donorId: donorId,
        recipientId: recipientId,
        requestStatus: 'pending',
        message: message,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final newId = await _dbService.createRequest(newRequest);
      
      // Update local request with real ID
      final createdRequest = newRequest.copyWith(requestId: newId);
      
      // Refresh requests (fetch from server to be sure, but also update local optimistically/safely)
      _myRequests.insert(0, createdRequest); // Add to top
      notifyListeners(); // Notify immediately so UI updates
      
      await fetchMyRequests(recipientId); // Fetch to sync completely
      
      _errorMessage = null;
      notifyListeners();
      return true;
    } catch (e) {
      _errorMessage = e.toString();
      notifyListeners();
      return false;
    } finally {
      _setLoading(false);
    }
  }

  Future<bool> acceptRequest(String requestId) async {
    return _updateRequestStatus(requestId, 'accepted');
  }

  Future<bool> rejectRequest(String requestId) async {
    return _updateRequestStatus(requestId, 'rejected');
  }

  Future<bool> completeRequest(String requestId) async {
    return _updateRequestStatus(requestId, 'completed');
  }

  Future<bool> cancelRequest(String requestId) async {
    return _updateRequestStatus(requestId, 'cancelled');
  }

  Future<bool> _updateRequestStatus(String requestId, String status) async {
    _setLoading(true);
    try {
      await _dbService.updateRequestStatus(requestId, status);
      
      // Update local lists
      final myIndex = _myRequests.indexWhere((r) => r.requestId == requestId);
      if (myIndex != -1) {
        _myRequests[myIndex] = _myRequests[myIndex].copyWith(requestStatus: status);
      }
      
      final incomingIndex = _incomingRequests.indexWhere((r) => r.requestId == requestId);
      if (incomingIndex != -1) {
        _incomingRequests[incomingIndex] = _incomingRequests[incomingIndex].copyWith(requestStatus: status);
      }
      
      _errorMessage = null;
      notifyListeners();
      return true;
    } catch (e) {
      _errorMessage = e.toString();
      notifyListeners();
      return false;
    } finally {
      _setLoading(false);
    }
  }

  void _setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }
}
