import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  late Map<String, String> _localizedStrings;

  // Simple map for now, can be moved to JSON files later
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Wajbat',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'register': 'Register',
      'full_name': 'Full Name', 
      'phone_number': 'Phone Number',
      'role': 'I want to:',
      'donor': 'Donate Food',
      'recipient': 'Receive Food',
      'organization_name': 'Organization Name (Optional)',
      'recipient_type': 'Recipient Type',
      'individual': 'Individual',
      'charity': 'Charity',
      'food_allergies': 'Food Allergies',
      'add_allergy_hint': 'e.g., peanuts, dairy',
      'add_allergy_desc': 'Add or remove ingredients you\'re allergic to.',
      'my_allergies': 'My Allergies',
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'language': 'Language',
      'notifications': 'Notifications',
      'help_center': 'Help Center (Chatbot)',
      'privacy_policy': 'Privacy Policy',
      'terms_conditions': 'Terms & Conditions',
      'contact_support': 'Contact Support',
      'logout': 'Logout',
      'delete_account': 'Delete Account',
      'save_changes': 'Save Changes',
      'currently': 'Currently:',
      'switch_role': 'Switch Role',
      'total_donations': 'Total\nDonations',
      'active_posts': 'Active\nPosts',
      'impact_score': 'Impact\nScore',
      'home': 'Home',
      'chat': 'Chat',
      'requests': 'Requests',
      'create_post': 'Create Post',
      'item_name': 'Item Name',
      'quantity': 'Quantity',
      'description': 'Description',
      'pickup_time': 'Pickup Time',
      'expiration_date': 'Expiration Date',
      'location': 'Location',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'warning': 'Warning',
      'allergy_warning': 'Allergy Warning',
      'contains_allergens': 'Contains: ',
      'request_this_food': 'Request This Food',
      'available': 'Available',
      'expired': 'Expired',
      // Added missing keys
      'welcome_back': 'Welcome Back',
      'create_account_title': 'Create Account',
      'browse': 'Browse',
      'my_posts': 'My Posts',
      'hello': 'Hello',
      'guest': 'Guest',
      'ready_to_make_difference': 'Ready to make a difference?',
      'find_food_near_you': 'Find food near you',
      'search_food': 'Search food...',
      'recent_posts': 'Recent Posts',
      'pending_requests': 'Pending Requests',
      'view_all': 'View All',
      'impact_points': 'Impact Points',
      'share_surplus_food': 'Share Surplus Food',
      'quickly_post_items': 'Quickly post items to help others.',
      'no_posts_yet': 'No posts yet',
      'start_sharing_surplus': 'Start sharing surplus food.',
      'no_pending_requests': 'No pending requests',
      'requests_appear_here': 'Requests will appear here.',
      'request_for': 'Request for',
      'status': 'Status: ',
      'donor_name': 'Donor Name',
      'expires': 'Expires: ',
      'exp': 'Exp: ',
      'filter_results': 'Filter Results',
      'distance_radius': 'Distance Radius',
      'sort_by': 'Sort By',
      'nearest': 'Nearest',
      'expiring_soon': 'Expiring Soon',
      'recently_added': 'Recently Added',
      'apply_filters': 'Apply Filters',
      'no_food_nearby': 'No food available nearby',
      'prepared_food': 'Prepared Food',
      'fruits_veggies': 'Fruits & Veggies',
      'bakery': 'Bakery',
      'groceries': 'Groceries',
      'other': 'Other',
      'all': 'All',
      'one_role_selection_warning': 'Only one role can be selected at a time',
      'my_profile': 'My Profile',
      'points': 'Points',
      'impact_high': 'High',
      'individual_donor': 'Individual Donor',
      'contains_allergen': 'Contains Allergen',
      'safe_ingredient': 'Safe Ingredient',
      'map_unavailable': 'Map preview unavailable',
      'open_in_maps': 'Open in Maps',
      'edit': 'Edit',
      'delete': 'Delete',
      'delete_post_title': 'Delete Post?',
      'delete_post_confirm': 'Are you sure you want to remove this food contribution?',
      'request_anyway': 'Request Anyway (I understand the risk)',
      'km': 'km',
      'request_message_hint': 'Add a message for the donor (optional)',
      'request_sent_success': 'Request sent successfully!',
      'request_send_failed': 'Failed to send request: ',
      'allergy_warning_desc': 'This food contains ingredients you are allergic to:',
      'allergy_proceed_confirm': 'Are you sure you want to proceed? Consuming this could be dangerous.',
      'post_deleted_success': 'Post deleted',
      'send_request': 'Send Request',
      'request_first': 'Please request the food first to start a chat.',
      'donor_not_loaded': 'Donor details not loaded yet.',
      'strength': 'Strength: ',
      'weak': 'Weak',
      'medium': 'Medium',
      'strong': 'Strong',
      'allergy_already_added': 'Allergy already added',
      'allergy_added': 'Allergy added',
      'select_role_error': 'Please select at least one role (Donate or Receive)',
      'accept_terms_error': 'You must accept the Terms and Conditions',
      'passwords_match_error': 'Passwords do not match',
      'confirm_password': 'Confirm Password',
      'reenter_password': 'Re-enter your password',
      'registration_failed': 'Registration failed',
      'terms_agree': 'I agree to the Terms and Conditions',
      'allergy_instruction': 'Add each ingredient separately. Tap + after typing each one.',
      'add_allergy': 'Add allergy',
      'delete_account_confirm_msg': 'This action is irreversible. All your data will be permanently removed.',
      'enter_password_confirm': 'Please enter your password to confirm:',
      'password_required': 'Password is required',
      'account_deleted_success': 'Account deleted successfully',
      'account_delete_failed': 'Failed to delete account: ',
      'incoming_requests_title': 'Incoming Requests',
      'my_requests_title': 'My Requests',
      'my_donations': 'My Donations',
      'available_food_title': 'Available Food',
      'pending': 'Pending',
      'accepted': 'Accepted',
      'rejected': 'Rejected',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'reserved': 'Reserved',
      'no_posts_found_filter': 'No {filter} posts found',
      'quantity_label': 'Quantity: ',
      'expires_label': 'Expires: ',
      'messages': 'Messages',
      'search_conversations': 'Search conversations...',
      'please_login_messages': 'Please login to view messages',
      'start_conversation': 'Start the conversation!',
      'type_a_message': 'Type a message...',
      'connection_lost': 'Real-time connection lost. Use refresh if needed.',
      'failed_load_messages': 'Failed to load messages: ',
      'failed_send_message': 'Failed to send: ',
      'request_status': 'Request Status: ',
      'no_incoming_requests_status': 'No {status} incoming requests',
      'no_requests_found_status': 'No {status} requests found',
      'accept_request_title': 'Accept Request?',
      'accept_request_desc': 'This will reserve the food for this recipient.',
      'reject_request_title': 'Reject Request?',
      'reject_request_desc': 'Are you sure you want to mark this request as rejected?',
      'mark_completed': 'Mark Completed',
      'accept': 'Accept',
      'reject': 'Reject',
      'confirm': 'Confirm',
      'request_updated': 'Request updated to ',
      'cancel_request': 'Cancel Request',
      'are_you_sure_cancel_request': 'Are you sure you want to cancel this food request?',
      'yes_cancel': 'Yes, Cancel',
      'no': 'No',
      'request_cancelled': 'Request cancelled',
      'mark_as_completed_title': 'Mark as Completed?',
      'mark_as_completed_desc': 'Has the food been successfully picked up?',
      'yes_completed': 'Yes, Completed',
      'leave_review': 'Leave Review',
      'for_item': 'For: ',
      'message_label': 'Message:',
      'loading': 'Loading...',
      'login_failed': 'Login failed',
      'how_continue': 'How would you like to continue?',
      'i_want_to_donate': 'I want to Donate',
      'i_need_food': 'I need Food',
      'failed_switch_role': 'Failed to switch role',
      'reset_password': 'Reset Password',
      'reset_password_desc': 'Enter your email address and we will send you a link to reset your password.',
      'send_reset_link': 'Send Reset Link',
      'password_reset_sent': 'Password reset link sent! Check your email.',
    },
    'ar': {
      'app_name': 'وجبات',
      'login': 'تسجيل الدخول',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'dont_have_account': 'ليس لديك حساب؟',
      'register': 'تسجيل جديد',
      'full_name': 'الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'role': 'أريد أن:',
      'donor': 'أتبرع بالطعام',
      'recipient': 'أستقبل الطعام',
      'organization_name': 'اسم المنظمة (اختياري)',
      'recipient_type': 'نوع المستفيد',
      'individual': 'فرد',
      'charity': 'جمعية خيرية',
      'food_allergies': 'حساسية الطعام',
      'add_allergy_hint': 'مثال: فول سوداني، حليب',
      'add_allergy_desc': 'أضف أو أزل المكونات التي لديك حساسية منها.',
      'my_allergies': 'حساسيتي',
      'profile': 'الملف الشخصي',
      'edit_profile': 'تعديل الملف الشخصي',
      'language': 'اللغة',
      'notifications': 'الإشعارات',
      'help_center': 'مركز المساعدة',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_conditions': 'الشروط والأحكام',
      'contact_support': 'تواصل مع الدعم',
      'logout': 'تسجيل الخروج',
      'delete_account': 'حذف الحساب',
      'save_changes': 'حفظ التغييرات',
      'currently': 'حالياً:',
      'switch_role': 'تغيير الدور',
      'total_donations': 'مجموع\nالتبرعات',
      'active_posts': 'الإعلانات\nالنشطة',
      'impact_score': 'نقاط\nالتأثير',
      'home': 'الرئيسية',
      'chat': 'المحادثات',
      'requests': 'الطلبات',
      'create_post': 'إضافة إعلان',
      'item_name': 'اسم العنصر',
      'quantity': 'الكمية',
      'description': 'الوصف',
      'pickup_time': 'وقت الاستلام',
      'expiration_date': 'تاريخ الانتهاء',
      'location': 'الموقع',
      'submit': 'إرسال',
      'cancel': 'إلغاء',
      'warning': 'تحذير',
      'allergy_warning': 'تحذير حساسية',
      'contains_allergens': 'يحتوي على: ',
      'request_this_food': 'طلب هذا الطعام',
      'available': 'متاح',
      'expired': 'منتهي',
      'select_language': 'اختر اللغة',
      // Added missing keys
      'welcome_back': 'مرحباً بعودتك',
      'create_account_title': 'إنشاء حساب',
      'browse': 'تصفح',
      'my_posts': 'إعلاناتي',
      'hello': 'مرحباً',
      'guest': 'ضيف',
      'ready_to_make_difference': 'مستعد لإحداث فرق؟',
      'find_food_near_you': 'ابحث عن طعام بالقرب منك',
      'search_food': 'ابحث عن طعام...',
      'recent_posts': 'أحدث الإعلانات',
      'pending_requests': 'الطلبات المعلقة',
      'view_all': 'عرض الكل',
      'impact_points': 'نقاط التأثير',
      'share_surplus_food': 'شارك الطعام الفائض',
      'quickly_post_items': 'اعرض العناصر بسرعة لمساعدة الآخرين.',
      'no_posts_yet': 'لا توجد إعلانات بعد',
      'start_sharing_surplus': 'ابدأ بمشاركة الطعام الفائض.',
      'no_pending_requests': 'لا توجد طلبات معلقة',
      'requests_appear_here': 'ستظهر الطلبات هنا.',
      'request_for': 'طلب لـ',
      'status': 'الحالة: ',
      'donor_name': 'اسم المتبرع',
      'expires': 'ينتهي: ',
      'exp': 'انتهاء: ',
      'filter_results': 'تصفية النتائج',
      'distance_radius': 'نطاق المسافة',
      'sort_by': 'ترتيب حسب',
      'nearest': 'الأقرب',
      'expiring_soon': 'ينتهي قريباً',
      'recently_added': 'أضيف مؤخراً',
      'apply_filters': 'تطبيق عوامل التصفية',
      'no_food_nearby': 'لا يوجد طعام متاح بالقرب منك',
      'prepared_food': 'طعام جاهز',
      'fruits_veggies': 'فواكه وخضروات',
      'bakery': 'مخبوزات',
      'groceries': 'بقالة',
      'other': 'أخرى',
      'all': 'الكل',
      'one_role_selection_warning': 'يمكن اختيار دور واحد فقط في كل مرة',
      'my_profile': 'ملفي الشخصي',
      'points': 'نقطة',
      'impact_high': 'عالي',
      'individual_donor': 'متبرع فردي',
      'contains_allergen': 'يحتوي على مسببات الحساسية',
      'safe_ingredient': 'مكون آمن',
      'map_unavailable': 'معاينة الخريطة غير متاحة',
      'open_in_maps': 'الفتح في الخرائط',
      'edit': 'تعديل',
      'delete': 'حذف',
      'delete_post_title': 'حذف الإعلان؟',
      'delete_post_confirm': 'هل أنت متأكد من رغبتك في حذف هذا العمل الخيري؟',
      'request_anyway': 'الطلب على أي حال (أنا أفهم المخاطر)',
      'km': 'كم',
      'request_message_hint': 'أضف رسالة للمتبرع (اختياري)',
      'request_sent_success': 'تم إرسال الطلب بنجاح!',
      'request_send_failed': 'فشل إرسال الطلب: ',
      'allergy_warning_desc': 'هذا الطعام يحتوي على مكونات لديك حساسية منها:',
      'allergy_proceed_confirm': 'هل أنت متأكد من المتابعة؟ قد يكون تناول هذا الطعام خطيراً.',
      'post_deleted_success': 'تم حذف الإعلان',
      'send_request': 'إرسال الطلب',
      'request_first': 'يرجى طلب الطعام أولاً لبدء المحادثة.',
      'donor_not_loaded': 'تفاصيل المتبرع لم يتم تحميلها بعد.',
      'strength': 'القوة: ',
      'weak': 'ضعيفة',
      'medium': 'متوسطة',
      'strong': 'قوية',
      'allergy_already_added': 'تمت إضافة هذه الحساسية بالفعل',
      'allergy_added': 'تمت إضافة الحساسية',
      'select_role_error': 'يرجى اختيار دور واحد على الأقل (تبرع أو استلام)',
      'accept_terms_error': 'يجب عليك قبول الشروط والأحكام',
      'passwords_match_error': 'كلمات المرور غير متطابقة',
      'confirm_password': 'تأكيد كلمة المرور',
      'reenter_password': 'أعد إدخال كلمة المرور',
      'registration_failed': 'فشل التسجيل',
      'terms_agree': 'أوافق على الشروط والأحكام',
      'allergy_instruction': 'أضف كل مكون على حدة. اضغط على + بعد كتابة كل واحد.',
      'add_allergy': 'إضافة حساسية',
      'delete_account_confirm_msg': 'هذا الإجراء لا يمكن التراجع عنه. سيتم حذف جميع بياناتك نهائياً.',
      'enter_password_confirm': 'يرجى إدخال كلمة المرور للتأكيد:',
      'password_required': 'كلمة المرور مطلوبة',
      'account_deleted_success': 'تم حذف الحساب بنجاح',
      'account_delete_failed': 'فشل حذف الحساب: ',
      'incoming_requests_title': 'الطلبات الواردة',
      'my_requests_title': 'طلباتي',
      'my_donations': 'تبرعاتي',
      'available_food_title': 'الطعام المتاح',
      'pending': 'معلق',
      'accepted': 'مقبول',
      'rejected': 'مرفوض',
      'completed': 'مكتمل',
      'cancelled': 'ملغى',
      'reserved': 'محجوز',
      'no_posts_found_filter': 'لا توجد منشورات {filter}',
      'quantity_label': 'الكمية: ',
      'expires_label': 'ينتهي: ',
      'messages': 'الرسائل',
      'search_conversations': 'البحث في المحادثات...',
      'please_login_messages': 'يرجى تسجيل الدخول لعرض الرسائل',
      'start_conversation': 'ابدأ المحادثة!',
      'type_a_message': 'اكتب رسالة...',
      'connection_lost': 'فقد الاتصال في الوقت الفعلي. استخدم التحديث إذا لزم الأمر.',
      'failed_load_messages': 'فشل تحميل الرسائل: ',
      'failed_send_message': 'فشل الإرسال: ',
      'request_status': 'حالة الطلب: ',
      'no_incoming_requests_status': 'لا توجد طلبات واردة {status}',
      'no_requests_found_status': 'لا توجد طلبات {status}',
      'accept_request_title': 'قبول الطلب؟',
      'accept_request_desc': 'سيؤدي هذا إلى حجز الطعام لهذا المستفيد.',
      'reject_request_title': 'رفض الطلب؟',
      'reject_request_desc': 'هل أنت متأكد أنك تريد وضع علامة مرفوض على هذا الطلب؟',
      'mark_completed': 'تحديد كمكتمل',
      'accept': 'قبول',
      'reject': 'رفض',
      'confirm': 'تأكيد',
      'request_updated': 'تم تحديث الطلب إلى ',
      'cancel_request': 'إلغاء الطلب',
      'are_you_sure_cancel_request': 'هل أنت متأكد أنك تريد إلغاء طلب الطعام هذا؟',
      'yes_cancel': 'نعم، إلغاء',
      'no': 'لا',
      'request_cancelled': 'تم إلغاء الطلب',
      'mark_as_completed_title': 'تحديد كمكتمل؟',
      'mark_as_completed_desc': 'هل تم استلام الطعام بنجاح؟',
      'yes_completed': 'نعم، اكتمل',
      'leave_review': 'ترك تقييم',
      'for_item': 'لـ: ',
      'message_label': 'الرسالة:',
      'loading': 'جاري التحميل...',
      'login_failed': 'فشل تسجيل الدخول',
      'how_continue': 'كيف تود المتابعة؟',
      'i_want_to_donate': 'أريد أن أتبرع',
      'i_need_food': 'أحتاج إلى طعام',
      'failed_switch_role': 'فشل في تغيير الدور',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'reset_password_desc': 'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور الخاصة بك.',
      'send_reset_link': 'إرسال رابط الإعادة',
      'password_reset_sent': 'تم إرسال رابط إعادة تعيين كلمة المرور! تحقق من بريدك الإلكتروني.',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  /// Translates dynamic values from backend (e.g. "donor", "individual")
  String translateDynamic(String? value) {
    if (value == null || value.isEmpty) return '';
    final key = value.toLowerCase().trim();
    // Special cases or direct mapping
    switch (key) {
      case 'donor': return translate('donor');
      case 'recipient': return translate('recipient');
      case 'individual': return translate('individual');
      case 'charity': return translate('charity');
      case 'high': return translate('impact_high');
      case 'points': return translate('points');
      default: return translate(key);
    }
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
